apiVersion: v1
kind: Service
metadata:
  name: story-app-service
  namespace: default
  labels:
    app: story-app
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      nodePort: 30500
  selector:
    app: story-app
  sessionAffinity: None
